# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build PCgen full

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 16
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build copyToOutput test compileSlowtest prepareRelease datatest pfinttest slowtest allReports buildDist
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 16
        cache: 'gradle'
    - name: Install nsis
      run: sudo apt install nsis
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew pcgenRelease
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/release/*"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
