name: Java CI

on: [schedule]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        distribution: adopt
        java-version: 16
    - name: Build with Gradle
      run: ./gradlew build
